name: mainplate
version: !include ./version.yaml
synopsis: Common patterns used for application main.
description: Common patterns used for application @main@.
maintainer: Peter Trško <peter.trsko@gmail.com>
copyright: (c) 2017-2020 Peter Trško
license: BSD3
license-file: LICENSE
github: trskop/mainplate
category: System, Options, CLI

extra-source-files:
  - ChangeLog.md
  - README.md
  - dhall/**/*.dhall

ghc-options:
  - -Wall
  - -Wcompat
  - -Wimplicit-prelude
  - -Wmissing-import-lists

default-extensions:
  - BlockArguments
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies

dependencies:
  - base >=4.9 && <5
  # ^ Version 4.9.0.0 is bundled with GHC 8.0.

  # Packages from Stackage+Hackage:
  - aeson
  - case-insensitive
  - dhall >= 1.33.0
  # ^ Inject/Interpret were renamed to ToDhall/FromDhall in version 1.27.0
  # (standard 11.0.0), we can't go below that now as we use the new names.
  #
  # Bultins `Optional/{fold,build}` were removed in version 1.33.0 (standard
  # 17.0.0), while this should not affect the code here, it does make binary
  # serialisation incompatible when it comes to more complicated use cases. To
  # prevent major issues we need to depend on at least this version.
  #
  # Version 1.36.0 added `Text/replace` and made `with` a first class citizen.
  # While we may want to depend on these features in the future, if we limit
  # our selves to standard 17.0.0 we should still be compatible, unlike in the
  # case of removed `Optional/{fold,build}`.
  - filepath
  - mtl
  - network
  - optparse-applicative
  - process
  - semver
  - terminfo
  - text
  - unordered-containers
  - verbosity
  - yaml

  # Other packages:
  - host-and-port >=0.0.1.0 && <1

library:
  source-dirs: src

# tests:
  # spec:
    # cpp-options: -DTEST
    # main: Spec.hs
    # source-dirs:
      # - test
      # - src
    # dependencies:
      # - hspec == 2.*
      # - QuickCheck
      # - temporary
      # - mockery >= 0.3
      # - interpolate
      # - aeson-qq
