name: mainplate
version: 0.0.1.0
synopsis: Common patterns used for application main.
description: Common patterns used for application @main@.
maintainer: Peter Trško <peter.trsko@gmail.com>
copyright: (c) 2017-2018 Peter Trško
license: BSD3
github: trskop/mainplate
category: System, Options, CLI

extra-source-files:
  - ChangeLog.md
  - README.md
  - dhall/ColourOutput/*
  - dhall/EnvironmentVariable/*

ghc-options:
  - -Wall

when:
  - condition: impl(GHC >8)
    then:
      ghc-options:
        - -Wimplicit-prelude
        - -Wmissing-import-lists
    else:
      # At some point these option will become obsolete.
      ghc-options:
        - -fwarn-implicit-prelude
        - -fwarn-missing-import-lists

dependencies:
  - base >=4.7 && <5

  # Packages from Stackage+Hackage:
  - aeson
  - case-insensitive
  - dhall >= 1.23.0  # Functional support of Dhall Standard 7.0.0
  - filepath
  - mtl
  - network
  - optparse-applicative
  - process
  - semver
  - terminfo
  - text
  - unordered-containers
  - verbosity
  - yaml

  # Other packages:
  - host-and-port

library:
  source-dirs: src

# tests:
  # spec:
    # cpp-options: -DTEST
    # main: Spec.hs
    # source-dirs:
      # - test
      # - src
    # dependencies:
      # - hspec == 2.*
      # - QuickCheck
      # - temporary
      # - mockery >= 0.3
      # - interpolate
      # - aeson-qq
