name: mainplate
version: 0.0.1.0
synopsis: Common patterns used for application main.
description: Common patterns used for application @main@.
maintainer: Peter Trško <peter.trsko@gmail.com>
license: BSD3
github: trskop/mainplate
category: System, Text

extra-source-files:
  - ChangeLog.md
  - README.md

ghc-options:
  - -Wall

when:
  - condition: impl(GHC >8)
    then:
      ghc-options:
        - -Wimplicit-prelude
        - -Wmissing-import-lists
    else:
      # At some point these option will become obsolete.
      ghc-options:
        - -fwarn-implicit-prelude
        - -fwarn-missing-import-lists

dependencies:
  - base >=4.7 && <5

  # Packages from Stackage+Hackage:
  - aeson
  - filepath
  - network
  - optparse-applicative
  - process
  - semver
  - text
  - verbosity
  - yaml

  # Other packages:
  - host-and-port

library:
  source-dirs: src
  exposed-modules:
    - Data.ConfigFile
    - Data.Output
    - Data.Version.Class
    - Mainplate
    - Mainplate.Core
    - Mainplate.Extensible
    - Options.Applicative.Standard
    - System.FilePath.Parse

tests:
  hlint-test-exe:
    main: hlint-test-exe.hs
    source-dirs:
      - test
    dependencies:
        hlint-test

  # spec:
    # cpp-options: -DTEST
    # main: Spec.hs
    # source-dirs:
      # - test
      # - src
    # dependencies:
      # - hspec == 2.*
      # - QuickCheck
      # - temporary
      # - mockery >= 0.3
      # - interpolate
      # - aeson-qq
