# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# (GHC 8.8.4)
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/20.yaml

packages:
  - .

extra-deps:
  - aeson-yaml-1.1.0.0
  - dhall-1.36.0
  - haskeline-0.8.1.0
  - prettyprinter-1.7.0
  - repline-0.4.0.0

  - git: https://github.com/trskop/host-and-port
    commit: 6ad44d8549822e12715531f860b17d0b608709d8

flags: {}
